### ISSUE TITLE
Alternative method for sorting results of map/filter

### ISSUE THREAD

**Issue by Rich-Harris** [vijithassar/object-iteration#4]
Wondering if there's a different way to sort objects than `create_comparator`. My concern is that with big objects (which is where this library would presumably be most useful — with lists that have unique IDs or timestamps as keys, etc) creating a comparator that uses `indexOf` is something like O(n^2) (I'm basically making that up, I don't speak big O, but you get my point).

Not sure what a better alternative looks like. Would probably need to have some kind of benchmarking suite before trying out different approaches anyway

**Comment by vijithassar** [comment]
[Fixed](https://github.com/vijithassar/object-iteration/commit/5c6f3d5813d0993ff5c81fa933afc3011254605a) in [v0.1.2](https://github.com/vijithassar/object-iteration/releases/tag/v0.1.2) by just passing the existing comparator function around instead of regenerating. I was probably trying to be a little too clever in an attempt to avoid adding yet another argument, but that's what currying is for.
